version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "reminder-app-api-aws"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1r6867evq8wjz"
s3_prefix = "reminder-app-api-aws"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
