AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  reminder-app-api-aws

  Sample SAM Template for reminder-app-api-aws

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 200
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 512
Resources:
  CreateReminderHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ReminderAppFunction
      Handler: com.caoguzelmas.aws.lambda.CreateReminderHandler::handleRequest
      Events:
        CreateUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /reminders
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ReminderAppApi:
    Description: "API Gateway endpoint URL for Prod stage for Reminder Application function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CreateReminderHandlerFunction:
    Description: "CreateReminderHandlerFunction Lambda Function ARN"
    Value: !GetAtt   CreateReminderHandlerFunction.Arn
  CreateReminderHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for CreateReminderHandlerFunction function"
    Value: !GetAtt CreateReminderHandlerFunction.Arn
