package com.caoguzelmas.aws.lambda.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.caoguzelmas.aws.lambda.model.enums.NotificationType;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

@Data
@Getter
@Setter
@DynamoDBTable(tableName = "reminders")
public class Reminder {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String reminderId;
   // private String userId;
   // private NotificationType notificationType;
    private String email;
    private String header;
    private String message;
    private Long timeToLive; // System.currentTimeMillis() / 1000L
}
